# Generated by Django 5.1.3 on 2024-11-10 04:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_completion_time', models.CharField(max_length=100)),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('proposed_price_copper', models.IntegerField(default=0)),
                ('in_game_name', models.CharField(max_length=100)),
                ('certification_level', models.CharField(choices=[('Novice', 'Novice'), ('Apprentice', 'Apprentice'), ('Journeyman', 'Journeyman'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date_bid', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50)),
                ('certification_level', models.CharField(max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_level', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(upload_to='certifications/')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(default='Unknown', max_length=20)),
                ('server', models.CharField(default='Server', max_length=20)),
                ('node', models.CharField(default='Node', max_length=20)),
                ('items_requested', models.TextField(default='No items specified')),
                ('item_category', models.CharField(choices=[('Alchemy', 'Alchemy'), ('Animal Husbandry', 'Animal Husbandry'), ('Arcane Engineering', 'Arcane Engineering'), ('Armor Smithing', 'Armor Smithing'), ('Carpentry', 'Carpentry'), ('Cooking', 'Cooking'), ('Farming', 'Farming'), ('Fishing', 'Fishing'), ('Herbalism', 'Herbalism'), ('Hunting', 'Hunting'), ('Jewel Cutting', 'Jewel Cutting'), ('Leatherworking', 'Leatherworking'), ('Lumberjacking', 'Lumberjacking'), ('Lumber Milling', 'Lumber Milling'), ('Metalworking', 'Metalworking'), ('Mining', 'Mining'), ('Scribing', 'Scribing'), ('Stonemasonry', 'Stonemasonry'), ('Tailoring', 'Tailoring'), ('Tanning', 'Tanning'), ('Weapon Smithing', 'Weapon Smithing'), ('Weaving', 'Weaving')], default='Alchemy', max_length=50)),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('total_copper', models.IntegerField(default=0)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('special_notes', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='posted', max_length=20)),
                ('accepted_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_jobs', to='api.bid')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.job'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('job_status', 'Job Status Update'), ('new_bid', 'New Bid'), ('bid_update', 'Bid Update'), ('job_update', 'Job Update'), ('service_request', 'Service Request'), ('cert_feedback', 'Certification Feedback')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('game_location', models.CharField(blank=True, max_length=30)),
                ('in_game_name', models.CharField(blank=True, max_length=30)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('recent_completed_jobs', models.TextField(default='[]')),
                ('can_create_store', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('total_copper', models.IntegerField(default=0)),
                ('timeline', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('feedback', 'Feedback Requested'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.job')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('services', models.CharField(max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
