# Generated by Django 5.1.3 on 2024-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bid_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
